### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Romz24** [AGraber/samp-037-compat#5]
If you enter a nickname longer than 21 characters, the server is turned off due to the fact that we go beyond the array.

The problem on this line is:
https://github.com/AGraber/samp-037-compat/blob/master/037-compat.inc#L29

I tried to increase the value of the array, this temporarily solves the problem. Maybe you know how to fix it better?

**Comment by Romz24** [comment]
**A similar problem with dl-compat.inc:**

```
[21:25:19] [debug] Server crashed while executing name.amx
[21:25:19] [debug] AMX backtrace:
[21:25:19] [debug] #0 native BS_ResetReadPointer () from pawnraknet.so
[21:25:19] [debug] #1 0000e02c in ?? (... <12 arguments>) at ..\gamemodes\include\other\dl-compat.inc:75
[21:25:19] [debug] #2 00000031 in public OnIncomingRPC () at D:\Programs\Pawno\include\float.inc:111
```

**Comment by AGraber** [comment]
I didn't expect this since default is 20 characters + null terminator. I'll assume you're using a plugin to allow this.

**Comment by Romz24** [comment]
I'm not using third-party plugins. I think that this is related to this code:
https://github.com/jovazxc/samp/blob/master/server/netrpc.cpp#L42

**Comment by karimcambridge** [comment]
@AGraber 

The default is 24 characters. (http://wiki.sa-mp.com/wiki/SetPlayerName)

But the server browser only allows 20.

A character name can never surpass 24 unless using something like YSF or something. So 25 is the safe spot.

**Comment by Romz24** [comment]
@karimcambridge 

I do not use YSF!

**Comment by AGraber** [comment]
@karimcambridge

The issue here is that, regardless of which is the limit, this include processes the name before the server itself. This means it does this even before the server can issue a "Unnacceptable Nickname" error. The max theoretical name could be of 256 characters (even if this is impossible for a normal user, but possible for an attacker). The include must be ready to receive that. I concluded that is not a plugin. Doing this also increases compatibility for includes that do this.

**Comment by karimcambridge** [comment]
Okay, cool. The issue seemed to be talking about the normal limits not the internet limits.
